slots:
  '1':
  - type: status
    values:
    - u
    - su
    enabled: true
    negate: true
  '2':
  - type: status
    values:
    - u
    - su
    - pu
    enabled: true
    negate: true
  '9':
  - type: status
    values:
    - pu
    enabled: true
    negate: true
  '3':
  - type: status
    values:
    - u
    - su
    - e
    enabled: true
    negate: true
  '4':
  - type: status
    values:
    - stoppeddl
    enabled: true
    negate: false
